const express=require("express");
const router=express.Router();
const { register, login,requestPasswordReset,resetPassword,getProfile,getUsers,getUser,updateUser,deleteUser,getPosts,getPostById,createPost,updatePost,deletePost } = require('../admin/admincontroller');
const authenticateJWT = require('../admin/adminMiddleware');
router.post("/signup",register);
router.post("/login",login);
router.post("/request-password-reset", requestPasswordReset);
router.post("/reset-password", resetPassword);
router.get("/profile", authenticateJWT, getProfile);
router.get("/users", authenticateJWT, getUsers);
router.get("/user/:id", authenticateJWT, getUser);
router.put("/user/:id", authenticateJWT, updateUser);
router.delete("/user/:id", authenticateJWT, deleteUser);
router.get("/posts", authenticateJWT, getPosts);
router.get("/post/:id", authenticateJWT, getPostById);
router.post("/post", authenticateJWT, createPost);
router.put("/post/:id", authenticateJWT, updatePost);
router.delete("/post/:id", authenticateJWT, deletePost);
module.exports=router;
